// ----- OUTPUTS -----
#define h 13
#define m 12
#define b 11
#define bg 10
#define bd 9
#define hg 8
#define hd 7
#define buzz 6

// ----- SETUP -----
void setup() {
    Serial.begin(9600);
    for(int i = 6; i < 14; i++) {
        pinMode(i, OUTPUT);
    }
}

// ----- NUMBERS -----
void num_1() {
    digitalWrite(h, LOW);
    digitalWrite(m, LOW);
    digitalWrite(b, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, LOW);
}

void num_2() {
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, LOW);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, LOW);
    digitalWrite(bg, HIGH);
}

void num_3() {
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, LOW);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, LOW);
}

void num_4() {
    digitalWrite(h, LOW);
    digitalWrite(m, HIGH);
    digitalWrite(b, LOW);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, LOW);
}

void num_5() {
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, LOW);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, LOW);
}

void num_6() {
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, LOW);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
}

void num_7() {
    digitalWrite(h, HIGH);
    digitalWrite(m, LOW);
    digitalWrite(b, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, LOW);
}

void num_8() {
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
}

void num_9() {
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, LOW);
}

void num_0() {
    digitalWrite(h, HIGH);
    digitalWrite(m, LOW);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
}

// ----- MODES -----
void compte() {
    num_1();
    delay(1000);
    num_2();
    delay(1000);
    num_3();
    delay(1000);
    num_4();
    delay(1000);
    num_5();
    delay(1000);
    num_6();
    delay(1000);
    num_7();
    delay(1000);
    num_8();
    delay(1000);
    num_9();
    delay(1000);
    num_0();
    delay(1000);
    digitalWrite(b, LOW);
    digitalWrite(m, LOW);
    digitalWrite(h, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, LOW);
    digitalWrite(bg, LOW);
    digitalWrite(bd, LOW);
}

void decompte() {
    delay(500);
    num_0();
    delay(1000);
    num_9();
    delay(1000);
    num_8();
    delay(1000);
    num_7();
    delay(1000);
    num_6();
    delay(1000);
    num_5();
    delay(1000);
    num_4();
    delay(1000);
    num_3();
    delay(1000);
    num_2();
    delay(1000);
    num_1();
    delay(1000);
    num_0();
    digitalWrite(buzz, HIGH);
    delay(150);
    digitalWrite(buzz,LOW);
    delay(150);
    digitalWrite(buzz, HIGH);
    delay(150);
    digitalWrite(buzz,LOW);
    digitalWrite(b, LOW);
    digitalWrite(m, LOW);
    digitalWrite(h, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, LOW);
    digitalWrite(bg, LOW);
    digitalWrite(bd, LOW);
}

void chain() {
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(100);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(100);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(100);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(100);
    digitalWrite(hd, LOW);
    delay(100);
}

void chain2() {
    delay(500);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(100);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(100);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(100);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(100);
    digitalWrite(hd, LOW);
    delay(100);
    digitalWrite(h, HIGH);
    delay(50);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(50);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(50);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(50);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(50);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(50);
    digitalWrite(hd, LOW);
    delay(50);
    digitalWrite(h, HIGH);
    delay(50);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(50);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(50);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(50);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(50);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(50);
    digitalWrite(hd, LOW);
    delay(50);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(100);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(100);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(100);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(100);
    digitalWrite(hd, LOW);
    delay(100);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(100);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(100);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(100);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(100);
    digitalWrite(hd, LOW);
    delay(100);
    digitalWrite(h, HIGH);
    delay(50);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(50);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(50);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(50);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(50);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(50);
    digitalWrite(hd, LOW);
    delay(50);
    digitalWrite(h, HIGH);
    delay(50);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(50);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(50);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(50);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(50);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(50);
    digitalWrite(hd, LOW);
    delay(50);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(100);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(100);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(100);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(100);
    digitalWrite(hd, LOW);
    delay(100);
    digitalWrite(b, LOW);
    digitalWrite(m, LOW);
    digitalWrite(h, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, LOW);
    digitalWrite(bg, LOW);
    digitalWrite(bd, LOW);
    delay(100);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(m, HIGH);
    delay(100);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(m, HIGH);
    delay(100);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(m, HIGH);
    delay(100);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(hg, HIGH);
    delay(100);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(bg, HIGH);
    delay(100);
    digitalWrite(m, HIGH);
    delay(100);
    digitalWrite(hd, HIGH);
    delay(100);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(bd, HIGH);
    delay(100);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(100);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(100);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(100);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(100);
    digitalWrite(hd, LOW);
    delay(100);
    digitalWrite(h, HIGH);
    delay(50);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(50);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(50);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(50);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(50);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(50);
    digitalWrite(hd, LOW);
    delay(50);
    digitalWrite(h, HIGH);
    delay(50);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(50);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(50);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(50);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(50);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(50);
    digitalWrite(hd, LOW);
    delay(50);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(100);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(100);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(100);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(100);
    digitalWrite(hd, LOW);
    delay(100);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(100);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(100);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(100);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(100);
    digitalWrite(hd, LOW);
    delay(100);
    digitalWrite(h, HIGH);
    delay(50);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(50);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(50);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(50);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(50);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(50);
    digitalWrite(hd, LOW);
    delay(50);
    digitalWrite(h, HIGH);
    delay(50);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(50);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(50);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(50);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(50);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(50);
    digitalWrite(hd, LOW);
    delay(50);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(h, LOW);
    digitalWrite(hg, HIGH);
    delay(100);
    digitalWrite(hg, LOW);
    digitalWrite(bg, HIGH);
    delay(100);
    digitalWrite(bg, LOW);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(b, LOW);
    digitalWrite(bd, HIGH);
    delay(100);
    digitalWrite(bd, LOW);
    digitalWrite(hd, HIGH);
    delay(100);
    digitalWrite(hd, LOW);
    delay(100);
    digitalWrite(b, LOW);
    digitalWrite(m, LOW);
    digitalWrite(h, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, LOW);
    digitalWrite(bg, LOW);
    digitalWrite(bd, LOW);
    delay(100);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(m, HIGH);
    delay(100);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(m, HIGH);
    delay(100);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(m, HIGH);
    delay(100);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(hg, HIGH);
    delay(100);
    digitalWrite(h, HIGH);
    delay(100);
    digitalWrite(bg, HIGH);
    delay(100);
    digitalWrite(m, HIGH);
    delay(100);
    digitalWrite(hd, HIGH);
    delay(100);
    digitalWrite(b, HIGH);
    delay(100);
    digitalWrite(bd, HIGH);
    delay(100);
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
    delay(500);
    digitalWrite(b, LOW);
    digitalWrite(m, LOW);
    digitalWrite(h, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, LOW);
    digitalWrite(bg, LOW);
    digitalWrite(bd, LOW);
    delay(500);
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
    delay(200);
    digitalWrite(b, LOW);
    digitalWrite(m, LOW);
    digitalWrite(h, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, LOW);
    digitalWrite(bg, LOW);
    digitalWrite(bd, LOW);
    delay(200);
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
    delay(100);
    digitalWrite(b, LOW);
    digitalWrite(m, LOW);
    digitalWrite(h, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, LOW);
    digitalWrite(bg, LOW);
    digitalWrite(bd, LOW);
    delay(100);
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
    delay(50);
    digitalWrite(b, LOW);
    digitalWrite(m, LOW);
    digitalWrite(h, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, LOW);
    digitalWrite(bg, LOW);
    digitalWrite(bd, LOW);
    delay(50);
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
    delay(10);
    digitalWrite(b, LOW);
    digitalWrite(m, LOW);
    digitalWrite(h, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, LOW);
    digitalWrite(bg, LOW);
    digitalWrite(bd, LOW);
    delay(10);
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
    delay(5);
    digitalWrite(b, LOW);
    digitalWrite(m, LOW);
    digitalWrite(h, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, LOW);
    digitalWrite(bg, LOW);
    digitalWrite(bd, LOW);
    delay(5);
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
    delay(5);
    digitalWrite(b, LOW);
    digitalWrite(m, LOW);
    digitalWrite(h, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, LOW);
    digitalWrite(bg, LOW);
    digitalWrite(bd, LOW);
    delay(5);
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
    delay(5);
    digitalWrite(b, LOW);
    digitalWrite(m, LOW);
    digitalWrite(h, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, LOW);
    digitalWrite(bg, LOW);
    digitalWrite(bd, LOW);
    delay(5);
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
    delay(5);
    digitalWrite(b, LOW);
    digitalWrite(m, LOW);
    digitalWrite(h, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, LOW);
    digitalWrite(bg, LOW);
    digitalWrite(bd, LOW);
    delay(5);
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
    delay(5);
    digitalWrite(b, LOW);
    digitalWrite(m, LOW);
    digitalWrite(h, LOW);
    digitalWrite(hg, LOW);
    digitalWrite(hd, LOW);
    digitalWrite(bg, LOW);
    digitalWrite(bd, LOW);
    delay(100);
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);  
}

// ----- LETTERS -----
void let_a() {
    digitalWrite(h, HIGH);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, LOW);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
}

void let_b() {
    digitalWrite(h, LOW);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, HIGH);
    digitalWrite(hd, LOW);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
}

void let_c() {
    digitalWrite(h, LOW);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, LOW);
    digitalWrite(hd, LOW);
    digitalWrite(bd, LOW);
    digitalWrite(bg, HIGH);
}

void let_d() {
    digitalWrite(h, LOW);
    digitalWrite(m, HIGH);
    digitalWrite(b, HIGH);
    digitalWrite(hg, LOW);
    digitalWrite(hd, HIGH);
    digitalWrite(bd, HIGH);
    digitalWrite(bg, HIGH);
}

void loop() {
    chain2();
}